pythonweb/moviepoll/urls.py
from django.urls import path

from . import views

# app_name = 'moviepoll'

# urlpatterns = [
#     path('', views.index, name='index'),
#     path('<int:question_id>/', views.detail, name='detail'),
#     path('<int:question_id>/results/', views.results, name='results'),
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]

app_name = 'moviepoll'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

pythonweb/pythonweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('moviepoll/', include('moviepoll.urls'))
]

pythonweb/moviepoll/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='Choices')
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

pythonweb/moviepoll/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic

from .models import Question, Choice

# Create your views here.

# def index(request):
#     lastest_question_list = Question.objects.order_by('-pub_date')[:5]
#     template = loader.get_template("moviepoll/index.html")
#     context = {
#         'lastest_question_list': lastest_question_list,
#         'haha': lastest_question_list
#     }
#     # output = ', '.join(q.question_text for q in lastest_question_list)
#     return HttpResponse(template.render(context, request))


# def detail(request, question_id):
#     # return HttpResponse("You're looking at question %s." % question_id)

#     #####################################################################
#     # try:
#     #     question = Question.objects.get(pk=question_id)
#     # except Question.DoesNotExist:
#     #     raise Http404("Question does not exist")
#     # return render(request, "moviepoll/detail.html", {'question': question})

#     #####################################################################
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "moviepoll/detail.html", {'question': question})
    


# def results(request, question_id):
#     # return HttpResponse("You're looking at the results of question %s." % question_id)
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'moviepoll/results.html', {'question': question})

# AMEND VIEWS

class IndexView(generic.ListView):
    template_name = 'moviepoll/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'moviepoll/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'moviepoll/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.Choices.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'moviepoll/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("moviepoll:results", args=(question.id,)))
    # return HttpResponse("You're voting on question %s." % question_id)

pythonweb/moviepoll/templates/moviepoll/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'moviepoll:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.Choices.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
    </form>

<!-- <ul>
{% for choice in question.Choices.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul> -->

pythonweb/moviepoll/templates/moviepoll/index.html
{% if lastest_question_list %}
    <ul>
        {% for question in lastest_question_list %}
        <!-- <li><a href="/moviepoll/{{ question.id }}/">{{ question.question_text }}</a></li> -->
        <li><a href="{% url 'moviepoll:detail' question.id%}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

pythonweb/moviepoll/templates/moviepoll/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.Choices.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'moviepoll:detail' question.id %}">Vote again?</a>